# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Ignore RVeg and Notebooks for now
exclude: (^rveg|^notebooks|^binder)
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: (^pyveg/configs|^pyveg/zenodo_config_template.py|^pyveg/azure_config_template.py)
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

# Ignore type checking for now, as this would require non-trival change to the code
# in order to pass `mypy` tests
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v0.960'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: mypy
