name: gee_pipeline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - earthengine-api
  - rasterio
  - coverage
  - icecream
  - gdal
  - arrow
  - azure-storage-blob==1.5.0
  - numpy
  - scipy
  - seaborn
  - pytest
  - requests
  - dateparser
  - python-igraph
  - pandas
  - geopandas
  - earthengine-api
  - pillow
  - imageio
  - statsmodels==0.11.1
  - pypandoc
  - pandoc
  - sphinx_rtd_theme
  - pyarrow
  - icecream
  - matplotlib

##########
####
####  # argparse
####  arrow
####  azure-storage-blob==1.5.0
####  # azure-storage-common==1.4.2
####  # azure-batch==6.0.0
####  # datetime
####  numpy
####  scipy
####  # matplotlib==3.1
####  seaborn
####  pytest
####  requests
####  dateparser
####  python-igraph
####  pandas
####  geopandas
####  earthengine-api
####  # geetools
####  pillow
####  imageio
####  # opencv-python
####  statsmodels==0.11.1
####  # ewstools
####  pypandoc
####  # mdutils
####  pandoc
####  sphinx_rtd_theme
####  pyarrow
####  icecream
####
